In [1]:
pip install -U textblob

Note: you may need to restart the kernel to use updated packages.


In [2]:
!pip install langdetect

In [3]:
pip install rake_nltk

Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd
import numpy as np

# keyword extraction and clean up
import nltk
from rake_nltk import Rake
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from nltk.stem import WordNetLemmatizer,PorterStemmer
import re

#Text Blob for sentiment analysis
from textblob import TextBlob

#tf-idf model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics.pairwise import linear_kernel

import string
import random
from PIL import Image
import requests
from io import BytesIO

from langdetect import detect

In [5]:
url= "https://ralston-hotel-data-bucket.s3.amazonaws.com/Hotel_Reviews_Clean.csv"

In [6]:
hotel_df = pd.read_csv(url)

In [7]:
hotel_df.head()

Unnamed: 0                                      Hotel_Address  \
0           0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
1           1   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
2           2   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
3           3   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
4           4   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   

   Additional_Number_of_Scoring Review_Date  Average_Score   Hotel_Name  \
0                           194  2017-08-03            7.7  Hotel Arena   
1                           194  2017-08-03            7.7  Hotel Arena   
2                           194  2017-07-31            7.7  Hotel Arena   
3                           194  2017-07-31            7.7  Hotel Arena   
4                           194  2017-07-24            7.7  Hotel Arena   

  Reviewer_Nationality                                    Negative_Review  \
0              Russia    I am so angry that i made this post available...   
1             Ireland                                         No Negative   
2           Australia    Rooms are nice but for elderly a bit difficul...   
3      United Kingdom    My room was dirty and I was afraid to walk ba...   
4         New Zealand    You When I booked with your company on line y...   

   Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  \
0                                397                     1403   
1                                  0                     1403   
2                                 42                     1403   
3                                210                     1403   
4                                140                     1403   

                                     Positive_Review  \
0   Only the park outside of the hotel was beauti...   
1   No real complaints the hotel was great great ...   
2   Location was good and staff were ok It is cut...   
3   Great location in nice surroundings the bar a...   
4    Amazing location and building Romantic setting    

   Review_Total_Positive_Word_Counts  \
0                                 11   
1                                105   
2                                 21   
3                                 26   
4                                  8   

   Total_Number_of_Reviews_Reviewer_Has_Given  Reviewer_Score  \
0                                           7             2.9   
1                                           7             7.5   
2                                           9             7.1   
3                                           1             3.8   
4                                           3             6.7   

                                                Tags days_since_review  \
0  [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days   
1  [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days   
2  [' Leisure trip ', ' Family with young childre...            3 days   
3  [' Leisure trip ', ' Solo traveler ', ' Duplex...            3 days   
4  [' Leisure trip ', ' Couple ', ' Suite ', ' St...           10 days   

         lat       lng Hotel_Country Sentiment  
0  52.360576  4.915968   Netherlands  Negative  
1  52.360576  4.915968   Netherlands  Positive  
2  52.360576  4.915968   Netherlands  Positive  
3  52.360576  4.915968   Netherlands  Negative  
4  52.360576  4.915968   Netherlands  Positive

In [8]:
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512470 entries, 0 to 512469
Data columns (total 20 columns):
 #   Column                                      Non-Null Count   Dtype  
---  ------                                      --------------   -----  
 0   Unnamed: 0                                  512470 non-null  int64  
 1   Hotel_Address                               512470 non-null  object 
 2   Additional_Number_of_Scoring                512470 non-null  int64  
 3   Review_Date                                 512470 non-null  object 
 4   Average_Score                               512470 non-null  float64
 5   Hotel_Name                                  512470 non-null  object 
 6   Reviewer_Nationality                        512470 non-null  object 
 7   Negative_Review                             512470 non-null  object 
 8   Review_Total_Negative_Word_Counts           512470 non-null  int64  
 9   Total_Number_of_Reviews                     512470 non-null  int64  
 

In [9]:
# combine reviews into one field
hotel_df["All_Reviews"] = hotel_df['Positive_Review'].astype(str) +"-"+ hotel_df["Negative_Review"]
hotel_df.head()

Unnamed: 0                                      Hotel_Address  \
0           0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
1           1   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
2           2   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
3           3   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
4           4   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   

   Additional_Number_of_Scoring Review_Date  Average_Score   Hotel_Name  \
0                           194  2017-08-03            7.7  Hotel Arena   
1                           194  2017-08-03            7.7  Hotel Arena   
2                           194  2017-07-31            7.7  Hotel Arena   
3                           194  2017-07-31            7.7  Hotel Arena   
4                           194  2017-07-24            7.7  Hotel Arena   

  Reviewer_Nationality                                    Negative_Review  \
0              Russia    I am so angry that i made this post available...   
1             Ireland                                         No Negative   
2           Australia    Rooms are nice but for elderly a bit difficul...   
3      United Kingdom    My room was dirty and I was afraid to walk ba...   
4         New Zealand    You When I booked with your company on line y...   

   Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  ...  \
0                                397                     1403  ...   
1                                  0                     1403  ...   
2                                 42                     1403  ...   
3                                210                     1403  ...   
4                                140                     1403  ...   

  Review_Total_Positive_Word_Counts  \
0                                11   
1                               105   
2                                21   
3                                26   
4                                 8   

   Total_Number_of_Reviews_Reviewer_Has_Given  Reviewer_Score  \
0                                           7             2.9   
1                                           7             7.5   
2                                           9             7.1   
3                                           1             3.8   
4                                           3             6.7   

                                                Tags days_since_review  \
0  [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days   
1  [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days   
2  [' Leisure trip ', ' Family with young childre...            3 days   
3  [' Leisure trip ', ' Solo traveler ', ' Duplex...            3 days   
4  [' Leisure trip ', ' Couple ', ' Suite ', ' St...           10 days   

         lat       lng  Hotel_Country Sentiment  \
0  52.360576  4.915968    Netherlands  Negative   
1  52.360576  4.915968    Netherlands  Positive   
2  52.360576  4.915968    Netherlands  Positive   
3  52.360576  4.915968    Netherlands  Negative   
4  52.360576  4.915968    Netherlands  Positive   

                                         All_Reviews  
0   Only the park outside of the hotel was beauti...  
1   No real complaints the hotel was great great ...  
2   Location was good and staff were ok It is cut...  
3   Great location in nice surroundings the bar a...  
4   Amazing location and building Romantic settin...  

[5 rows x 21 columns]

In [10]:
hotel_unique_df = hotel_df.drop_duplicates('Hotel_Name')
hotel_unique_df.head()

Unnamed: 0                                      Hotel_Address  \
0              0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
405          405  1 15 Templeton Place Earl s Court Kensington a...   
971          971  1 2 Serjeant s Inn Fleet Street City of London...   
2008        2008  1 3 Queens Garden Westminster Borough London W...   
3778        3778    1 3 Rue d Argentine 16th arr 75116 Paris France   

      Additional_Number_of_Scoring Review_Date  Average_Score  \
0                              194  2017-08-03            7.7   
405                            244  2017-08-03            8.5   
971                            639  2017-08-02            9.2   
2008                          1058  2017-08-02            7.7   
3778                            26  2017-06-29            8.4   

                            Hotel_Name Reviewer_Nationality  \
0                          Hotel Arena              Russia    
405                   K K Hotel George             Ireland    
971            Apex Temple Court Hotel      United Kingdom    
2008  The Park Grand London Paddington              Cyprus    
3778               Monhotel Lounge SPA              Brazil    

                                        Negative_Review  \
0      I am so angry that i made this post available...   
405     Really nothing negative to say about this hotel   
971    Difficult to locate the phone to contact rece...   
2008   The first night we were given an extremely sm...   
3778                                        No Negative   

      Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  ...  \
0                                   397                     1403  ...   
405                                   9                     1831  ...   
971                                  20                     2619  ...   
2008                                 30                     4380  ...   
3778                                  0                      171  ...   

     Review_Total_Positive_Word_Counts  \
0                                   11   
405                                 18   
971                                 17   
2008                                 6   
3778                               231   

      Total_Number_of_Reviews_Reviewer_Has_Given  Reviewer_Score  \
0                                              7             2.9   
405                                            2             9.6   
971                                            1             9.2   
2008                                           6             8.3   
3778                                           1             9.2   

                                                   Tags days_since_review  \
0     [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days   
405   [' Leisure trip ', ' Group ', ' Classic Twin R...            0 days   
971   [' Leisure trip ', ' Couple ', ' Deluxe King R...            1 days   
2008  [' Family with young children ', ' Triple Room...            1 days   
3778  [' Leisure trip ', ' Group ', ' Comfort Double...           35 days   

            lat       lng  Hotel_Country Sentiment  \
0     52.360576  4.915968    Netherlands  Negative   
405   51.491888 -0.194971             UK  Positive   
971   51.513734 -0.108751             UK  Positive   
2008  51.514218 -0.180903             UK  Positive   
3778  48.874348  2.289733         France  Positive   

                                            All_Reviews  
0      Only the park outside of the hotel was beauti...  
405    Very comfortable beds smart bathroom good sho...  
971    They have followed through special requests C...  
2008   The size of the room- The first night we were...  
3778   Nice hotel Room was beautiful and bed very co...  

[5 rows x 21 columns]

In [11]:
hotel_unique_df.Hotel_Name.value_counts()

Hotel Arena                      1
Hotel 55                         1
Steigenberger Hotel Herrenhof    1
Hotel J ger                      1
Senator Hotel Vienna             1
                                ..
The Cleveland                    1
Grange Buckingham Hotel          1
Hilton London Olympia            1
H tel De Castiglione             1
Atlantis Hotel Vienna            1
Name: Hotel_Name, Length: 1475, dtype: int64

In [12]:
hotel_unique_df = hotel_unique_df.reset_index(drop=True)
hotel_unique_df.head()

Unnamed: 0                                      Hotel_Address  \
0           0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
1         405  1 15 Templeton Place Earl s Court Kensington a...   
2         971  1 2 Serjeant s Inn Fleet Street City of London...   
3        2008  1 3 Queens Garden Westminster Borough London W...   
4        3778    1 3 Rue d Argentine 16th arr 75116 Paris France   

   Additional_Number_of_Scoring Review_Date  Average_Score  \
0                           194  2017-08-03            7.7   
1                           244  2017-08-03            8.5   
2                           639  2017-08-02            9.2   
3                          1058  2017-08-02            7.7   
4                            26  2017-06-29            8.4   

                         Hotel_Name Reviewer_Nationality  \
0                       Hotel Arena              Russia    
1                  K K Hotel George             Ireland    
2           Apex Temple Court Hotel      United Kingdom    
3  The Park Grand London Paddington              Cyprus    
4               Monhotel Lounge SPA              Brazil    

                                     Negative_Review  \
0   I am so angry that i made this post available...   
1    Really nothing negative to say about this hotel   
2   Difficult to locate the phone to contact rece...   
3   The first night we were given an extremely sm...   
4                                        No Negative   

   Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  ...  \
0                                397                     1403  ...   
1                                  9                     1831  ...   
2                                 20                     2619  ...   
3                                 30                     4380  ...   
4                                  0                      171  ...   

  Review_Total_Positive_Word_Counts  \
0                                11   
1                                18   
2                                17   
3                                 6   
4                               231   

   Total_Number_of_Reviews_Reviewer_Has_Given  Reviewer_Score  \
0                                           7             2.9   
1                                           2             9.6   
2                                           1             9.2   
3                                           6             8.3   
4                                           1             9.2   

                                                Tags days_since_review  \
0  [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days   
1  [' Leisure trip ', ' Group ', ' Classic Twin R...            0 days   
2  [' Leisure trip ', ' Couple ', ' Deluxe King R...            1 days   
3  [' Family with young children ', ' Triple Room...            1 days   
4  [' Leisure trip ', ' Group ', ' Comfort Double...           35 days   

         lat       lng  Hotel_Country Sentiment  \
0  52.360576  4.915968    Netherlands  Negative   
1  51.491888 -0.194971             UK  Positive   
2  51.513734 -0.108751             UK  Positive   
3  51.514218 -0.180903             UK  Positive   
4  48.874348  2.289733         France  Positive   

                                         All_Reviews  
0   Only the park outside of the hotel was beauti...  
1   Very comfortable beds smart bathroom good sho...  
2   They have followed through special requests C...  
3   The size of the room- The first night we were...  
4   Nice hotel Room was beautiful and bed very co...  

[5 rows x 21 columns]

In [13]:
#data pre-processing to remove stop words, punctuation, white space, and convert all words to lower case from combined reviews
hotel_unique_pp_df = hotel_unique_df.copy()
key_words = []
name_key_words = []

r = Rake()

for index, row in hotel_unique_pp_df.iterrows():
    r.extract_keywords_from_text(row['All_Reviews'])
    key_words_dict_scores = r.get_word_degrees()
    keywords = list(key_words_dict_scores.keys())
    
    key_words.append(keywords)

    r.extract_keywords_from_text(row['Hotel_Name'])
    key_words_dict_scores = r.get_word_degrees()
    name_keywords = list(key_words_dict_scores.keys())
    
    name_key_words.append(name_keywords)
    
hotel_unique_pp_df["key_words"] = key_words
hotel_unique_pp_df["name_key_words"] = name_key_words

hotel_unique_pp_df.head()

Unnamed: 0                                      Hotel_Address  \
0           0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
1         405  1 15 Templeton Place Earl s Court Kensington a...   
2         971  1 2 Serjeant s Inn Fleet Street City of London...   
3        2008  1 3 Queens Garden Westminster Borough London W...   
4        3778    1 3 Rue d Argentine 16th arr 75116 Paris France   

   Additional_Number_of_Scoring Review_Date  Average_Score  \
0                           194  2017-08-03            7.7   
1                           244  2017-08-03            8.5   
2                           639  2017-08-02            9.2   
3                          1058  2017-08-02            7.7   
4                            26  2017-06-29            8.4   

                         Hotel_Name Reviewer_Nationality  \
0                       Hotel Arena              Russia    
1                  K K Hotel George             Ireland    
2           Apex Temple Court Hotel      United Kingdom    
3  The Park Grand London Paddington              Cyprus    
4               Monhotel Lounge SPA              Brazil    

                                     Negative_Review  \
0   I am so angry that i made this post available...   
1    Really nothing negative to say about this hotel   
2   Difficult to locate the phone to contact rece...   
3   The first night we were given an extremely sm...   
4                                        No Negative   

   Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  ...  \
0                                397                     1403  ...   
1                                  9                     1831  ...   
2                                 20                     2619  ...   
3                                 30                     4380  ...   
4                                  0                      171  ...   

  Reviewer_Score                                               Tags  \
0            2.9  [' Leisure trip ', ' Couple ', ' Duplex Double...   
1            9.6  [' Leisure trip ', ' Group ', ' Classic Twin R...   
2            9.2  [' Leisure trip ', ' Couple ', ' Deluxe King R...   
3            8.3  [' Family with young children ', ' Triple Room...   
4            9.2  [' Leisure trip ', ' Group ', ' Comfort Double...   

   days_since_review        lat       lng Hotel_Country  Sentiment  \
0             0 days  52.360576  4.915968   Netherlands   Negative   
1             0 days  51.491888 -0.194971            UK   Positive   
2             1 days  51.513734 -0.108751            UK   Positive   
3             1 days  51.514218 -0.180903            UK   Positive   
4            35 days  48.874348  2.289733        France   Positive   

                                         All_Reviews  \
0   Only the park outside of the hotel was beauti...   
1   Very comfortable beds smart bathroom good sho...   
2   They have followed through special requests C...   
3   The size of the room- The first night we were...   
4   Nice hotel Room was beautiful and bed very co...   

                                           key_words  \
0  [park, outside, hotel, beautiful, angry, made,...   
1  [comfortable, beds, smart, bathroom, good, sho...   
2  [followed, special, requests, comfortable, bed...   
3  [size, room, first, night, given, extremely, s...   
4  [nice, hotel, room, beautiful, bed, comfortabl...   

                      name_key_words  
0                     [hotel, arena]  
1                 [k, hotel, george]  
2       [apex, temple, court, hotel]  
3  [park, grand, london, paddington]  
4            [monhotel, lounge, spa]  

[5 rows x 23 columns]

In [14]:
hotel_unique_pp_clean_df = hotel_unique_pp_df.copy()

In [15]:
# clean up keywords: drop symbols and numbers, as well as find root words

lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer() 

def preprocess(sentence):
    sentence=str(sentence)
    sentence = sentence.lower()
    sentence=sentence.replace('{html}',"") 
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', sentence)
    rem_url=re.sub(r'http\S+', '',cleantext)
    rem_num = re.sub('[0-9]+', '', rem_url)
    tokenizer = RegexpTokenizer(r'\w+')
    tokens = tokenizer.tokenize(rem_num)  
    filtered_words = [w for w in tokens if len(w) > 2 if not w in stopwords.words('english')]
    stem_words=[stemmer.stem(w) for w in filtered_words]
    lemma_words=[lemmatizer.lemmatize(w) for w in stem_words]
    return " ".join(filtered_words)


hotel_unique_pp_clean_df['clean_keywords']=hotel_unique_pp_clean_df['key_words'].map(lambda s:preprocess(s)) 
hotel_unique_pp_clean_df.head()

Unnamed: 0                                      Hotel_Address  \
0           0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
1         405  1 15 Templeton Place Earl s Court Kensington a...   
2         971  1 2 Serjeant s Inn Fleet Street City of London...   
3        2008  1 3 Queens Garden Westminster Borough London W...   
4        3778    1 3 Rue d Argentine 16th arr 75116 Paris France   

   Additional_Number_of_Scoring Review_Date  Average_Score  \
0                           194  2017-08-03            7.7   
1                           244  2017-08-03            8.5   
2                           639  2017-08-02            9.2   
3                          1058  2017-08-02            7.7   
4                            26  2017-06-29            8.4   

                         Hotel_Name Reviewer_Nationality  \
0                       Hotel Arena              Russia    
1                  K K Hotel George             Ireland    
2           Apex Temple Court Hotel      United Kingdom    
3  The Park Grand London Paddington              Cyprus    
4               Monhotel Lounge SPA              Brazil    

                                     Negative_Review  \
0   I am so angry that i made this post available...   
1    Really nothing negative to say about this hotel   
2   Difficult to locate the phone to contact rece...   
3   The first night we were given an extremely sm...   
4                                        No Negative   

   Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  ...  \
0                                397                     1403  ...   
1                                  9                     1831  ...   
2                                 20                     2619  ...   
3                                 30                     4380  ...   
4                                  0                      171  ...   

                                                Tags  days_since_review  \
0  [' Leisure trip ', ' Couple ', ' Duplex Double...             0 days   
1  [' Leisure trip ', ' Group ', ' Classic Twin R...             0 days   
2  [' Leisure trip ', ' Couple ', ' Deluxe King R...             1 days   
3  [' Family with young children ', ' Triple Room...             1 days   
4  [' Leisure trip ', ' Group ', ' Comfort Double...            35 days   

         lat       lng Hotel_Country Sentiment  \
0  52.360576  4.915968   Netherlands  Negative   
1  51.491888 -0.194971            UK  Positive   
2  51.513734 -0.108751            UK  Positive   
3  51.514218 -0.180903            UK  Positive   
4  48.874348  2.289733        France  Positive   

                                         All_Reviews  \
0   Only the park outside of the hotel was beauti...   
1   Very comfortable beds smart bathroom good sho...   
2   They have followed through special requests C...   
3   The size of the room- The first night we were...   
4   Nice hotel Room was beautiful and bed very co...   

                                           key_words  \
0  [park, outside, hotel, beautiful, angry, made,...   
1  [comfortable, beds, smart, bathroom, good, sho...   
2  [followed, special, requests, comfortable, bed...   
3  [size, room, first, night, given, extremely, s...   
4  [nice, hotel, room, beautiful, bed, comfortabl...   

                      name_key_words  \
0                     [hotel, arena]   
1                 [k, hotel, george]   
2       [apex, temple, court, hotel]   
3  [park, grand, london, paddington]   
4            [monhotel, lounge, spa]   

                                      clean_keywords  
0  park outside hotel beautiful angry made post a...  
1  comfortable beds smart bathroom good shower lo...  
2  followed special requests comfortable bed wide...  
3  size room first night given extremely small ba...  
4  nice hotel room beautiful bed comfortable expe...  

[5 rows x 24 columns]

In [16]:
hotel_sub_df = hotel_unique_pp_clean_df.copy()

In [17]:
# run text blob in a loop

polarities = []
subjectivities = []

for index, row in hotel_sub_df.iterrows():
    sentence = row['All_Reviews']
    analysis = TextBlob(sentence).sentiment
    polarity = analysis[0]
    subjectivity = analysis[1]

    # populate lists
    polarities.append(polarity)
    subjectivities.append(subjectivity)


hotel_sub_df['sentiment_polarity'] = polarities
hotel_sub_df['sentiment_subjectivity']= subjectivities

hotel_sub_df.head()

Unnamed: 0                                      Hotel_Address  \
0           0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
1         405  1 15 Templeton Place Earl s Court Kensington a...   
2         971  1 2 Serjeant s Inn Fleet Street City of London...   
3        2008  1 3 Queens Garden Westminster Borough London W...   
4        3778    1 3 Rue d Argentine 16th arr 75116 Paris France   

   Additional_Number_of_Scoring Review_Date  Average_Score  \
0                           194  2017-08-03            7.7   
1                           244  2017-08-03            8.5   
2                           639  2017-08-02            9.2   
3                          1058  2017-08-02            7.7   
4                            26  2017-06-29            8.4   

                         Hotel_Name Reviewer_Nationality  \
0                       Hotel Arena              Russia    
1                  K K Hotel George             Ireland    
2           Apex Temple Court Hotel      United Kingdom    
3  The Park Grand London Paddington              Cyprus    
4               Monhotel Lounge SPA              Brazil    

                                     Negative_Review  \
0   I am so angry that i made this post available...   
1    Really nothing negative to say about this hotel   
2   Difficult to locate the phone to contact rece...   
3   The first night we were given an extremely sm...   
4                                        No Negative   

   Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  ...        lat  \
0                                397                     1403  ...  52.360576   
1                                  9                     1831  ...  51.491888   
2                                 20                     2619  ...  51.513734   
3                                 30                     4380  ...  51.514218   
4                                  0                      171  ...  48.874348   

        lng  Hotel_Country  Sentiment  \
0  4.915968    Netherlands   Negative   
1 -0.194971             UK   Positive   
2 -0.108751             UK   Positive   
3 -0.180903             UK   Positive   
4  2.289733         France   Positive   

                                         All_Reviews  \
0   Only the park outside of the hotel was beauti...   
1   Very comfortable beds smart bathroom good sho...   
2   They have followed through special requests C...   
3   The size of the room- The first night we were...   
4   Nice hotel Room was beautiful and bed very co...   

                                           key_words  \
0  [park, outside, hotel, beautiful, angry, made,...   
1  [comfortable, beds, smart, bathroom, good, sho...   
2  [followed, special, requests, comfortable, bed...   
3  [size, room, first, night, given, extremely, s...   
4  [nice, hotel, room, beautiful, bed, comfortabl...   

                      name_key_words  \
0                     [hotel, arena]   
1                 [k, hotel, george]   
2       [apex, temple, court, hotel]   
3  [park, grand, london, paddington]   
4            [monhotel, lounge, spa]   

                                      clean_keywords sentiment_polarity  \
0  park outside hotel beautiful angry made post a...           0.046438   
1  comfortable beds smart bathroom good shower lo...           0.267698   
2  followed special requests comfortable bed wide...           0.014354   
3  size room first night given extremely small ba...           0.050000   
4  nice hotel room beautiful bed comfortable expe...           0.259738   

  sentiment_subjectivity  
0               0.452243  
1               0.591799  
2               0.668776  
3               0.388889  
4               0.450035  

[5 rows x 26 columns]

In [18]:
hotel_sub_df.Hotel_Name.value_counts()

Hotel Arena                      1
Hotel 55                         1
Steigenberger Hotel Herrenhof    1
Hotel J ger                      1
Senator Hotel Vienna             1
                                ..
The Cleveland                    1
Grange Buckingham Hotel          1
Hilton London Olympia            1
H tel De Castiglione             1
Atlantis Hotel Vienna            1
Name: Hotel_Name, Length: 1475, dtype: int64

In [19]:
#imports
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import linear_kernel

In [20]:
tfidf = TfidfVectorizer(stop_words='english',smooth_idf=True)

# numbers to calculate similarities
tfidf_matrix = tfidf.fit_transform(hotel_sub_df['clean_keywords']).todense()

In [21]:
tfidf_matrix

matrix([[0.        , 0.        , 0.07687068, ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]])

In [22]:
#calculate cosine matrix
cosine_similarities = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(cosine_similarities)

C:\Users\16513\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


[[1.         0.02775123 0.         ... 0.04576608 0.01198679 0.01373626]
 [0.02775123 1.         0.01933517 ... 0.00948075 0.         0.0231052 ]
 [0.         0.01933517 1.         ... 0.         0.         0.        ]
 ...
 [0.04576608 0.00948075 0.         ... 1.         0.         0.00624459]
 [0.01198679 0.         0.         ... 0.         1.         0.00428577]
 [0.01373626 0.0231052  0.         ... 0.00624459 0.00428577 1.        ]]


In [23]:
indices = pd.Series(hotel_sub_df['Hotel_Name'])

In [24]:
#get recommendations based on tf-idf and cosine_similarities (hotel name)

def recommend_name(Hotel_Name, cosine_similarities = cosine_similarities):
    
    recommended_hotel = []
    recommended_hotel_address = []
    recommended_hotel_rating = []
    recommended_hotel_score = []
         
    idx = indices[indices == Hotel_Name].index[0]
    
    score_series = pd.Series(cosine_similarities[idx]).sort_values(ascending = False)
    
    top_10_indices = list(score_series.iloc[1:11].index)
    
    for i in top_10_indices:
        recommended_hotel.append(list(hotel_sub_df['Hotel_Name'])[i])
        recommended_hotel_address.append(list(hotel_sub_df['Hotel_Address'])[i])
        recommended_hotel_rating.append(list(hotel_sub_df['Average_Score'])[i])
        recommended_hotel_score.append(score_series[i])
        
    data = {'Hotel': recommended_hotel,
           'Address': recommended_hotel_address,
            'Rating': recommended_hotel_rating,
            'Score': recommended_hotel_score
                       }
    
    rec_df = pd.DataFrame(data)
    
    return rec_df

In [25]:
rec_filter_df = recommend_name('Copthorne Tara Hotel London Kensington')
rec_filter_df = rec_filter_df[(rec_filter_df['Rating'] > 8)]
rec_filter_df.head()

Hotel  \
0           The Chamberlain   
1              Caesar Hotel   
2           Primero Primera   
3      The Cavendish London   
4  The Westbourne Hyde Park   

                                             Address  Rating     Score  
0  130 135 Minories City of London London EC3N 1N...     8.9  0.207321  
1  26 33 Queens Gardens Westminster Borough Londo...     8.2  0.179883  
2  Doctor Carulla 25 Sarri St Gervasi 08017 Barce...     9.2  0.172148  
3  81 Jermyn Street Westminster Borough London SW...     8.8  0.158376  
4  51 Gloucester Terrace Westminster Borough Lond...     8.9  0.153060

In [26]:
# prepping for Flask

In [27]:
#code that stays consistent
url= "https://ralston-hotel-data-bucket.s3.amazonaws.com/Hotel_Reviews_Clean.csv"
hotel_df = pd.read_csv(url)

tfidf = TfidfVectorizer(stop_words='english',smooth_idf=True)
tfidf_matrix = tfidf.fit_transform(hotel_sub_df['clean_keywords']).todense()

cosine_similarities = cosine_similarity(tfidf_matrix, tfidf_matrix)

C:\Users\16513\anaconda3\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


In [28]:
np.save("hotel_cos_data.npy", cosine_similarities)

In [29]:
hotel_arr = np.load("hotel_cos_data.npy")

In [30]:
print(hotel_arr[0:5])

[[1.         0.02775123 0.         ... 0.04576608 0.01198679 0.01373626]
 [0.02775123 1.         0.01933517 ... 0.00948075 0.         0.0231052 ]
 [0.         0.01933517 1.         ... 0.         0.         0.        ]
 [0.03748136 0.03275728 0.         ... 0.04752206 0.00767096 0.0059227 ]
 [0.06073488 0.07644466 0.04567874 ... 0.05012176 0.04066727 0.03397718]]


In [31]:
#uploaded .npy arr file to S3 bucket
hotel_arr_url = "https://ralston-hotel-data-bucket.s3.amazonaws.com/hotel_cos_data.npy"

In [32]:
pip install s3fs

Note: you may need to restart the kernel to use updated packages.


In [33]:
import s3fs

In [34]:
s3 = s3fs.S3FileSystem(anon=True)

In [35]:
hotel_arr_s3 = np.load(s3.open("ralston-hotel-data-bucket/hotel_cos_data.npy"))

In [36]:
print(hotel_arr_s3[0:5])

[[1.         0.02775123 0.         ... 0.04576608 0.01198679 0.01373626]
 [0.02775123 1.         0.01933517 ... 0.00948075 0.         0.0231052 ]
 [0.         0.01933517 1.         ... 0.         0.         0.        ]
 [0.03748136 0.03275728 0.         ... 0.04752206 0.00767096 0.0059227 ]
 [0.06073488 0.07644466 0.04567874 ... 0.05012176 0.04066727 0.03397718]]


In [37]:
#example variable
Hotel_Name = "Primero Primera"


#variable reliant code
indices = pd.Series(hotel_sub_df['Hotel_Name'])

recommended_hotel = []
recommended_hotel_address = []
recommended_hotel_rating = []
recommended_hotel_score = []

idx = indices[indices == Hotel_Name].index[0]

score_series = pd.Series(cosine_similarities[idx]).sort_values(ascending = False)

top_10_indices = list(score_series.iloc[1:11].index)

for i in top_10_indices:
    recommended_hotel.append(list(hotel_sub_df['Hotel_Name'])[i])
    recommended_hotel_address.append(list(hotel_sub_df['Hotel_Address'])[i])
    recommended_hotel_rating.append(list(hotel_sub_df['Average_Score'])[i])
    recommended_hotel_score.append(score_series[i])
    

data = {'Hotel': recommended_hotel,
        'Address': recommended_hotel_address,
        'Rating': recommended_hotel_rating,
        'Score': recommended_hotel_score
        }

rec_df = pd.DataFrame(data)
rec_df = rec_df[(rec_df['Rating'] > 5)]

rec_df


Hotel  \
0          Crowne Plaza Amsterdam South   
1                   Ramada Plaza Milano   
2  Club Quarters Hotel Trafalgar Square   
3                               Bassano   
4          Le Parisis Paris Tour Eiffel   
5                                Amp re   
6       Hotel Spa Villa Olimpica Suites   
7            Crowne Plaza London Ealing   
8     Corendon Vitality Hotel Amsterdam   
9                 Le Narcisse Blanc Spa   

                                             Address  Rating     Score  
0  George Gershwinlaan 101 Zuideramstel 1082 MT A...     9.0  0.312552  
1  Via Stamira D Ancona 27 Distretto Viale Monza ...     8.4  0.243432  
2  8 Northumberland Avenue Westminster Borough Lo...     8.5  0.242138  
3      15 Rue de Bassano 16th arr 75016 Paris France     8.3  0.219235  
4     102 Bd De Grenelle 15th arr 75015 Paris France     8.6  0.206636  
5  102 Avenue de Villiers 17th arr 75017 Paris Fr...     8.8  0.204313  
6    Pallars 121 125 Sant Mart 08018 Barcelona Spain     8.0  0.200575  
7             Western Avenue Ealing London W5 1HG UK     8.5  0.199171  
8  Aletta Jacobslaan 7 Slotervaart 1066 BP Amster...     8.4  0.199009  
9  19 Boulevard De La Tour Maubourg 7th arr 75007...     9.5  0.195490